name: CI - Auto-merge

on:
  pull_request:
  merge_group:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: 
    uses: ./.github/workflows/ci-auto-merge.yaml
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

