name: 🎉 Create Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: ./.github/workflows/create-release.yaml
    secrets:
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
