name: 🧹 Stale repository identifier

on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  contents: read
  issues: write

jobs:
  stale-repository-identifier:
    uses: ./.github/workflows/stale-repository-identifier.yaml
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
