name: 🔄 Sync Labels

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

permissions: {}

jobs:
  sync:
    permissions:
      contents: read
      issues: write
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: 🔄 Sync labels
        uses: devantler-tech/actions/sync-github-labels@55e9a09c265e68c601e22c44be8b9ec8d817cabb # v3.2.1
