name: 🔄 Sync labels

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight


permissions:
  issues: write

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: 🔄 Sync labels
        uses: ./composite-actions/sync-labels-action
