name: CI - Test .NET solution or project
permissions:
  packages: read
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
      APP_PRIVATE_KEY:
        required: true
  ### Required Workflow Triggers ###
  pull_request:
  merge_group:
  ##################################

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    # Ignore Require Workflow runs
    if: github.repository != 'devantler-tech/reusable-workflows'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: 📑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🧪 Test .NET solution or project
        uses: devantler-tech/actions/dotnet-test-action@884a9b7321e269351d5fc006d95e0b50b2ddedf6 # v1.9.7
        with:
          app_id: ${{ vars.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
