name: CI - GitOps Validate

on:
  workflow_call:
  ### Required Workflow Triggers ###
  pull_request:
  merge_group:
  ##################################

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    # Ignore Require Workflow runs
    if: github.repository != 'devantler-tech/reusable-workflows'
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: ⚙️ Setup KSail
        uses: devantler-tech/actions/setup-ksail-action@884a9b7321e269351d5fc006d95e0b50b2ddedf6 # v1.9.7

      - name: 🧹 Validate GitOps cluster configuration
        run: |
          ksail workload validate
