name: CI - GitOps Test

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      KSAIL_SOPS_KEY:
        required: false
    inputs:
      RUNNER:
        required: false
        type: string
        default: ubuntu-latest
      DISTRIBUTION:
        required: false
        type: string
        default: Talos
      PROVIDER:
        required: false
        type: string
        default: Docker
      HOSTS_FILE:
        required: false
        type: string
      ROOT_CA_CERT_FILE:
        required: false
        type: string
      SKIP:
        required: false
        type: boolean
      VALIDATE:
        required: false
        type: boolean
        default: true
  ### Required Workflow Triggers ###
  pull_request:
  merge_group:
  ##################################

jobs:
  test:
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    # Ignore Require Workflow runs
    if: github.repository != 'devantler-tech/reusable-workflows' && inputs.SKIP != true && github.event_name != 'merge_group'
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🧪 Run GitOps test
        uses: devantler-tech/ksail/.github/actions/ksail-cluster@78d8e01cfeb3bb7b8c5ff2f30d24eebc9371cf65 # feat/ksail-cluster-end-user-support
        with:
          distribution: ${{ inputs.DISTRIBUTION || 'Talos' }}
          provider: ${{ inputs.PROVIDER || 'Docker' }}
          init: "false"
          validate: ${{ inputs.VALIDATE && 'true' || 'false' }}
          sops-age-key: ${{ secrets.KSAIL_SOPS_KEY }}
          hosts-file: ${{ inputs.HOSTS_FILE || vars.HOSTS_FILE }}
          root-ca-cert-file: ${{ inputs.ROOT_CA_CERT_FILE || vars.ROOT_CA_CERT_FILE }}
          push: "true"
          reconcile: "true"
          delete: "true"
