name: Delete Workflow Runs

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to target for workflow run deletion"
        required: false
        default: ${{ github.repository }}
        type: string
      days:
        description: "Days-worth of runs to keep for each workflow"
        required: false
        default: 30
        type: number
      minimum_runs:
        description: "Minimum runs to keep for each workflow"
        required: false
        default: 6
        type: number
      delete_workflow_pattern:
        description: "Name or filename of the workflow (if not set, all workflows are targeted)"
        required: false
        type: string
      delete_workflow_by_state_pattern:
        description: |
          Filter workflows by state:
            - ALL, active, deleted, disabled_fork, disabled_inactivity, disabled_manually
          Accepts a comma-separated list of states.
        required: false
        default: "ALL"
        type: string
      delete_run_by_conclusion_pattern:
        description: |
          Remove runs based on conclusion:
            - ALL, action_required, cancelled, failure, skipped, success
          Accepts a comma-separated list of conclusions.
        required: false
        default: "ALL"
        type: string
      dry_run:
        description: "Logs simulated changes, no deletions are performed"
        required: false
        type: boolean

permissions: {}

jobs:
  delete-runs:
    name: Delete workflow runs
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: 🗑️ Delete workflow runs
        uses: Mattraks/delete-workflow-runs@5bf9a1dac5c4d041c029f0a8370ddf0c5cb5aeb7 # v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ inputs.repository }}
          retain_days: ${{ inputs.days }}
          keep_minimum_runs: ${{ inputs.minimum_runs }}
          delete_workflow_pattern: ${{ inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ inputs.delete_workflow_by_state_pattern }}
          delete_run_by_conclusion_pattern: ${{ inputs.delete_run_by_conclusion_pattern }}
          dry_run: ${{ inputs.dry_run }}
