name: 🗑️ Delete Workflow Runs

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to target for workflow run deletion (defaults to the calling repository)"
        required: false
        type: string
      days:
        description: "Days-worth of runs to keep for each workflow"
        required: false
        default: 30
        type: number
      minimum-runs:
        description: "Minimum runs to keep for each workflow"
        required: false
        default: 6
        type: number
      delete-workflow-pattern:
        description: "Name or filename of the workflow (if not set, all workflows are targeted)"
        required: false
        type: string
      delete-workflow-by-state-pattern:
        description: |
          Filter workflows by state:
            - ALL, active, deleted, disabled_fork, disabled_inactivity, disabled_manually
          Accepts a comma-separated list of states.
        required: false
        default: "ALL"
        type: string
      delete-run-by-conclusion-pattern:
        description: |
          Remove runs based on conclusion:
            - ALL, action_required, cancelled, failure, skipped, success
          Accepts a comma-separated list of conclusions.
        required: false
        default: "ALL"
        type: string
      dry-run:
        description: "Logs simulated changes, no deletions are performed"
        required: false
        default: true
        type: boolean

permissions: {}

jobs:
  delete-runs:
    name: Delete workflow runs
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: 🗑️ Delete workflow runs
        uses: Mattraks/delete-workflow-runs@b3018382ca039b53d238908238bd35d1fb14f8ee # v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ inputs.repository || github.repository }}
          retain_days: ${{ inputs.days }}
          keep_minimum_runs: ${{ inputs.minimum-runs }}
          delete_workflow_pattern: ${{ inputs.delete-workflow-pattern }}
          delete_workflow_by_state_pattern: ${{ inputs.delete-workflow-by-state-pattern }}
          delete_run_by_conclusion_pattern: ${{ inputs.delete-run-by-conclusion-pattern }}
          dry_run: ${{ inputs.dry-run }}
