name: 🧹 Lint Documentation

on:
  workflow_call:
    secrets:
      app-private-key:
        description: "GitHub App Private Key"
        required: true
  ### Required Workflow Triggers ###
  pull_request:
  merge_group:
  ##################################

permissions: {}

jobs:
  lint:
    name: 🧹 Lint - mega-linter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: 🔑 Generate GitHub App Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: generate-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.app-private-key }}

      - name: 📄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
          token: ${{ steps.generate-token.outputs.token }}

      - name: 🧹 Lint
        id: ml
        uses: oxsecurity/megalinter/flavors/documentation@8fbdead70d1409964ab3d5afa885e18ee85388bb # v9.4.0
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLY_FIXES: all
          APPLY_FIXES_EVENT: all
          APPLY_FIXES_MODE: commit

      - name: 💾 Commit and push applied linter fixes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "chore: Apply megalinter fixes"
          commit_user_name: megalinter-bot
          commit_user_email: 129584137+megalinter-bot@users.noreply.github.com
