name: CI - GitOps Validate

on:
  workflow_call:
  ### Required Workflow Triggers ###
  pull_request:
  merge_group:
  ##################################

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    # Ignore Require Workflow runs
    if: github.repository != 'devantler-tech/reusable-workflows'
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: ⚙️ Setup KSail
        uses: devantler-tech/composite-actions/setup-ksail-action@b2d85eefa2d5a75ee53571910e29080c5bdd271a # v1.9.0

      - name: 🧹 Validate GitOps cluster configuration
        run: |
          ksail validate
