name: "TODOs"

on:
  workflow_call:
    secrets:
      APP_PRIVATE_KEY:
        required: true

permissions:
  issues: write
jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 🧪 Run todos-action
        uses: devantler-tech/github-actions/composite-actions/todos-action@d69de4b313f789d5aff0bf42614da212fc5362e2 # v1.8.4
        with:
          APP_ID: ${{ vars.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          PROJECT: organization/devantler-tech/5
