name: CI - Auto-merge

on:
  workflow_call:
  ### Required Workflow Triggers ###
  pull_request:
  merge_group:
  ##################################

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Ignore Require Workflow runs
    if: github.repository != 'devantler-tech/github-actions' && startsWith(github.event_name, 'pull_request') && !github.event.pull_request.draft && (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'botantler[bot]' || github.event.pull_request.user.login == 'devantler' || github.event.pull_request.user.login == 'Copilot')
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 🔀 Auto-merge
        uses: devantler-tech/github-actions/composite-actions/auto-merge-action@d69de4b313f789d5aff0bf42614da212fc5362e2 # v1.8.4
        with:
          app_id: ${{ vars.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
