name: CI - GitOps Test (Flux)

on:
  workflow_call:
    secrets:
      KSAIL_SOPS_KEY:
        required: false
    inputs:
      HOSTS_FILE:
        required: false
        type: string
      ROOT_CA_CERT_FILE:
        required: false
        type: string
  ### Required Workflow Triggers ###
  pull_request:
  merge_group:
  ##################################

jobs:
  test:
    runs-on: ubuntu-latest
    # Ignore Require Workflow runs
    if: github.repository != 'devantler-tech/github-actions'
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: ⚙️ Setup KSail
        uses: devantler-tech/github-actions/composite-actions/setup-ksail-action@d69de4b313f789d5aff0bf42614da212fc5362e2 # v1.8.4

      - name: 🌐 Add hosts
        run: |
          if [ -f "${{ inputs.HOSTS_FILE || vars.HOSTS_FILE }}" ]; then
            sudo tee -a /etc/hosts < "${{ inputs.HOSTS_FILE || vars.HOSTS_FILE }}"
          fi

      - name: 🔐 Install root CA
        run: |
          if [ -f "${{ inputs.ROOT_CA_CERT_FILE || vars.ROOT_CA_CERT_FILE }}" ]; then
            sudo cp "${{ inputs.ROOT_CA_CERT_FILE || vars.ROOT_CA_CERT_FILE }}" /usr/local/share/ca-certificates/root-ca.crt
            sudo update-ca-certificates
          fi

      - name: 🔑 Import Age key
        env:
          KSAIL_SOPS_KEY: ${{ secrets.KSAIL_SOPS_KEY }}
        if: ${{ env.KSAIL_SOPS_KEY != '' }}
        run: ksail secrets import "${{ secrets.KSAIL_SOPS_KEY }}"

      - name: 🚀 Provision cluster
        run: |
          ksail up

      - name: 🔥 Teardown cluster
        if: always()
        run: ksail down
