name: 🧪 Run .NET Tests

permissions: {}

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
      APP_PRIVATE_KEY:
        required: true
  ### Required Workflow Triggers ###
  pull_request:
  merge_group:
  ##################################

jobs:
  test:
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    # Ignore Require Workflow runs
    if: github.repository != 'devantler-tech/reusable-workflows'
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🧪 Test .NET solution or project
        uses: devantler-tech/actions/run-dotnet-tests@961f62f4a771b31e48acaae4a619cef6c7fe2195 # v2.1.1
        with:
          app-id: ${{ vars.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
