name: "[Test] Zizmor"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: "test-zizmor-${{ github.event.number || 'manual' }}"
  cancel-in-progress: true

permissions: {}

jobs:
  test-zizmor:
    name: "[Test] Zizmor - Default Settings"
    uses: ./.github/workflows/zizmor.yaml
    permissions:
      security-events: write
      contents: read
      actions: read

  test-zizmor-status:
    name: "[Test] Zizmor - Status"
    runs-on: ubuntu-latest
    needs: [test-zizmor]
    permissions: {}
    if: ${{ !cancelled() }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Check test results
        run: |
          if [[ "$TEST_RESULT" != "success" && "$TEST_RESULT" != "skipped" ]]; then
            echo "❌ One or more tests failed"
            exit 1
          else
            echo "✅ All tests passed successfully"
          fi
        env:
          TEST_RESULT: ${{ needs.test-zizmor.result }}
