name: TODOs

on:
  workflow_call:
    secrets:
      APP_PRIVATE_KEY:
        required: true

permissions:
  issues: write

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: 📑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🧪 Run todos-action
        uses: devantler-tech/actions/todos-action@884a9b7321e269351d5fc006d95e0b50b2ddedf6 # v1.9.7
        with:
          APP_ID: ${{ vars.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          PROJECT: organization/devantler-tech/5
